source 'https://rubygems.org'
ruby "2.7.4"
gem 'sinatra'
gem 'slim'
gem 'sassc'
gem 'dm-core'
gem 'dm-migrations'
gem 'thin'
gem 'dm-mysql-adapter'
gem 'stripe'
gem 'json'
gem 'dotenv'
gem 'activerecord'
gem 'mysql2'

gem 'sinatra-reloader'